[ase]
name = "ASE"
desc = "Australian Securities Exchange"

[abs]
name = "ABS"
desc = "Asset-backed security"

[ads]
name = "ADS"
desc = "American Depositary Shares"

[adr]
name = "ADR"
desc = "American Depositary Receipts"

[amex]
name = "AMEX"
desc = "American Stock Exchange"

[aba]
name = "ABA"
desc = "American Bankers Association"
