[bg]
name = "BG"
desc = "Business Group"
see = ["BU"]

[bu]
name = "BU"
desc = "Business Unit"
see = ["BG"]

[bse.Beijing]
name = "BSE"
desc = "Beijing Stock Exchange"

[bse.India]
name = "BSE"
desc = "Bombay Stock Exchange"
see = 'NSE'

[bdi]
name = "BDI"
desc = "Baltic Dry Index"

[bba]
name = "BBA"
desc = "Bachelor of Business Administration"

[boll]
name = "BOLL"
desc = "Bollinger Bands"

[bop]
name = "BOP"
desc = "Balance of Payments"

[bp]
name = "BP"
desc = "Basis Point 0.01%"

[bpm]
name = "BPM"
desc = "Business Process Management"

[bp.plan]
name = "BP"
desc = "Business Plan"
