[bg]
disp = "BG"
desc = "Business Group"
see = ["BU"]

[bu]
disp = "BU"
desc = "Business Unit"
see = ["BG"]

[bse]
disp = "BSE"
desc = "Beijing Stock Exchange"

[bdi]
disp = "BDI"
desc = "Baltic Dry Index"

[bba]
disp = "BBA"
desc = "Bachelor of Business Administration"
