[bg]
disp = "BG"
desc = "Business Group"
full = "业务集团"
see = ["BU"]

[bu]
disp = "BU"
desc = "Business Unit"
full = "经营单元"
see = ["BG"]

[bse]
disp = "BSE"
desc = "Beijing Stock Exchange"
full = "北京证券交易所（北交所）"