[cpi]
name = "CPI"
desc = "Consumer Price Index"

[cfa]
name = "CFA"
desc = "Chartered Financial Analyst"

[cpa]
name = "CPA"
desc = "Certified Practising Accountant"

[csi]
name = "CSI"
desc = "China Securities Index"

[cbot]
name = "CBOT"
desc = "Chicago Board of Trade"

[cboe]
name = "CBOE"
desc = "Chicago Board Options Exchange"

[cme]
name = "CME"
desc = "Chicago Mercantile Exchange"

[cmo.officer]
name = "CMO"
desc = "Chief Marketing Officer"

[cmo.pharmaceutical]
name = "CMO"
desc = "Contract Manufacturing Organization"

[cdmo.pharmaceutical]
name = "CDMO"
desc = "Contract Development and Manufacturing Organization"

[cso.pharmaceutical]
name = "CSO"
desc = "Contract Sales Organization"

[cfd]
name = "CFD"
desc = "Contract for Differences"

[cds]
name = "CDS"
desc = "Credit Default Swap"

[cac]
name = "CAC40"
desc = "Cotation Assistée en Continu (French stock market index)"

[cci]
name = "CCI"
desc = "Commodity Channel Index"

[cffex]
name = "CFFEX"
desc = "China Financial Futures Exchange"

[czce]
name = "CZCE"
desc = "Zhengzhou Commodity Exchange"

[cosco]
name = "COSCO"
desc = "China Ocean Shipping Company"

[ccc]
name = "CCC"
desc = "Cash Conversion Cycle"

[cusip]
name = "CUSIP"
desc = "Committee on Uniform Securities Identification Procedures"
more = "A nine-digit code that uniquely identifies a security in the United States. CUSIP codes are assigned by the American Bankers Association (ABA) and are used by financial institutions to track securities."
see = 'ISIN'

[cogs]
name = "COGS"
desc = "Cost of Goods Sold"

[cfo]
name = "CFO"
desc = "Cash Flow of Operating"
see = ['CFI', 'CFF']

[cfi]
name = "CFI"
desc = "Cash Flow of Investing"
see = ['CFO', 'CFF']

[cff]
name = "CFF"
desc = "Cash Flow of Financing"
see = ['CFO', 'CFI']

[cagr]
name = "CAGR"
desc = "Compound Annual Growth Rate"

[c2m]
name = "C2M"
desc = "Consumer To Manufacturer"
