[cpi]
disp = "CPI"
desc = "Consumer Price Index"

[cfa]
disp = "CFA"
desc = "Chartered Financial Analyst"

[cpa]
disp = "CPA"
desc = "Certified Practising Accountant"

[csi]
disp = "CSI"
desc = "China Securities Index"

[cbot]
disp = "CBOT"
desc = "Chicago Board of Trade"

[cboe]
disp = "CBOE"
desc = "Chicago Board Options Exchange"

[cme]
disp = "CME"
desc = "Chicago Mercantile Exchange"

[cmo.officer]
disp = "CMO"
desc = "Chief Marketing Officer"

[cmo.pharmaceutical]
disp = "CMO"
desc = "Contract Manufacturing Organization"

[cdmo.pharmaceutical]
disp = "CDMO"
desc = "Contract Development and Manufacturing Organization"

[cso.pharmaceutical]
disp = "CSO"
desc = "Contract Sales Organization"

[cfd]
disp = "CFD"
desc = "Contract for Differences"

[cds]
disp = "CDS"
desc = "Credit Default Swap"

[cac]
disp = "CAC40"
desc = "Cotation Assistée en Continu (French stock market index)"

[cci]
disp = "CCI"
desc = "Commodity Channel Index"

[cffex]
disp = "CFFEX"
desc = "China Financial Futures Exchange"

[czce]
disp = "CZCE"
desc = "Zhengzhou Commodity Exchange"
