[cpi]
disp = "CPI"
desc = "Consumer Price Index"

[cfa]
disp = "CFA"
desc = "Chartered Financial Analyst"

[cpa]
disp = "CPA"
desc = "Certified Practising Accountant"

[csi]
disp = "CSI"
desc = "China Securities Index"
