[cpi]
name = "CPI"
desc = "Consumer Price Index"

[cfa]
name = "CFA"
desc = "Chartered Financial Analyst"

[cpa]
name = "CPA"
desc = "Certified Practising Accountant"

[csi]
name = "CSI"
desc = "China Securities Index"

[cbot]
name = "CBOT"
desc = "Chicago Board of Trade"

[cboe]
name = "CBOE"
desc = "Chicago Board Options Exchange"

[cme]
name = "CME"
desc = "Chicago Mercantile Exchange"

[cmo.officer]
name = "CMO"
desc = "Chief Marketing Officer"

[cmo.pharmaceutical]
name = "CMO"
desc = "Contract Manufacturing Organization"

[cdmo.pharmaceutical]
name = "CDMO"
desc = "Contract Development and Manufacturing Organization"

[cso.pharmaceutical]
name = "CSO"
desc = "Contract Sales Organization"

[cfd]
name = "CFD"
desc = "Contract for Differences"

[cds]
name = "CDS"
desc = "Credit Default Swap"

[cac]
name = "CAC40"
desc = "Cotation Assistée en Continu (French stock market index)"

[cci]
name = "CCI"
desc = "Commodity Channel Index"

[cffex]
name = "CFFEX"
desc = "China Financial Futures Exchange"

[czce]
name = "CZCE"
desc = "Zhengzhou Commodity Exchange"

[cosco]
name = "COSCO"
desc = "China Ocean Shipping Company"
