[dex]
name = "DEX"
desc = "Decentralized Exchanges"

[dax]
name = "DAX"
desc = "Deutscher Aktienindex (German stock index)"
see = ["FTSE","DJIA"]

[djia]
name = "DJIA"
desc = "Dow Jones Industrial Average"

[dpo]
name = "DPO"
desc = "Direct Public Offering"

[dce]
name = "DCE"
desc = "Dalian Commodity Exchange"

[dd]
name = "DD"
desc = "Due Diligence"

[dcf]
name = "DCF"
desc = "Discounted Cash Flow"

[dau]
name = "DAU"
desc = "Daily Active User"
see = 'MAU'
