[etp]
name = "ETP"
desc = "Exchange-Traded Product"

[etf]
name = "ETF"
desc = "Exchange-Traded Fund"

[etn]
name = "ETN"
desc = "Exchange-Traded Notes"

[etc]
name = "ETC"
desc = "Exchange-Traded Commodities"

[ecn]
name = "ECN"
desc = "Electronic Communication Network"
more = "A digital system that matches buyers and sellers looking to trade securities in the financial markets"

[eps]
name = "EPS"
desc = "Earnings Per Share"

[ea]
name = "EA"
desc = "Expert Advisor"

[ems]
name = "EMS"
desc = "European Monetary System"

[emba]
name = "EMBA"
desc = "Executive Master of Business Administration"

[ebitda]
name = "EBITDA"
desc = "Earnings Before Interest, Taxes, Depreciation and Amortization"

[ev]
name = "EV"
desc = "Enterprise Value"

[ecm]
name = "ECM"
desc = "Enterprise Content Management"

[edgar]
name = "EDGAR"
desc = "Electronic Data Gathering, Analysis, and Retrieval System"

[esg]
name = "ESG"
desc = "Environmental, Social, and Governance"
more = "It is a framework used to assess an organization's business practices and performance on various sustainability and ethical issues. It also provides a way to measure business risks and opportunities in those areas"
