[etf]
name = "ETF"
desc = "Exchange-traded Fund"

[eps]
name = "EPS"
desc = "Earnings Per Share"

[ea]
name = "EA"
desc = "Expert Advisor"

[ems]
name = "EMS"
desc = "European Monetary System"

[emba]
name = "EMBA"
desc = "Executive Master of Business Administration"

[ebitda]
name = "EBITDA"
desc = "Earnings Before Interest, Taxes, Depreciation and Amortization"

[ev]
name = "EV"
desc = "Enterprise Value"

[ecm]
name = "ECM"
desc = "Enterprise Content Management"
