[fred]
disp = "FRED"
desc = "Federal Reserve Economic Data"

[fof]
disp = "FOF"
desc = "fund of funds"

[ftse]
disp = "FTSE"
desc = "Financial Times Stock Exchange"

[frm]
disp = "FRM"
desc = "Financial Risk Manager"

[fdi]
disp = "FDI"
desc = "Foreign Direct Investment"
