[fred]
name = "FRED"
desc = "Federal Reserve Economic Data"

[fof]
name = "FOF"
desc = "fund of funds"

[ftse]
name = "FTSE"
desc = "Financial Times Stock Exchange"

[frm]
name = "FRM"
desc = "Financial Risk Manager"

[fdi]
name = "FDI"
desc = "Foreign Direct Investment"
see = ['ODI']
