[gnp]
name = "GNP"
desc = "Gross National Product"

[gni]
name = "GNI"
desc = "Gross National Income"

[gbp]
name = "GBP"
desc = "Great British Pound"

[gp]
name = "GP"
desc = "General Partner"

[gips]
name = "GIPS"
desc = "Global Investment Performance Standards"

[gatt]
name = "GATT"
desc = "General Agreement on Tariffs and Trade"
