[gnp]
disp = "GNP"
desc = "Gross National Product"

[gni]
disp = "GNI"
desc = "Gross National Income"

[gbp]
disp = "GBP"
desc = "Great British Pound"

[gp]
disp = "GP"
desc = "General Partner"

[gips]
disp = "GIPS"
desc = "Global Investment Performance Standards"

[gatt]
disp = "GATT"
desc = "General Agreement on Tariffs and Trade"
