[hkex]
name = "HKEX"
desc = "Hong Kong Exchanges and Clearing"

[hsi]
name = "HSI"
desc = "Hang Seng Index"

[hdi]
name = "HDI"
desc = "Human Development Index"

[hsbc]
name = "HSBC"
desc = "the Hongkong and Shanghai Banking Corporation Group"
more = "A British multinational investment bank and financial services holding company"
