[hkex]
disp = "HKEX"
desc = "Hong Kong Exchanges and Clearing"

[hsi]
disp = "HSI"
desc = "Hang Seng Index"

[hdi]
disp = "HDI"
desc = "Human Development Index"

[hsbc]
disp = "HSBC"
desc = "the Hongkong and Shanghai Banking Corporation Group"
full = "A British multinational investment bank and financial services holding company"
