[imf]
disp = "IMF"
desc = "International Monetary Fund"

[imm]
disp = "IMM"
desc = "International Monetary Market"

[ibex]
disp = "IBEX35"
desc = "IBerian IndEX"

[idc]
disp = "IDC"
desc = "Interactive Data Corporation"
