[imf]
name = "IMF"
desc = "International Monetary Fund"

[imm]
name = "IMM"
desc = "International Monetary Market"

[ibex]
name = "IBEX35"
desc = "IBerian IndEX"

[idc]
name = "IDC"
desc = "Interactive Data Corporation"

[ifi]
name = "IFI"
desc = "Information Sciences Institute"

[ip]
name = "IP"
desc = "Intellectual Property"

[ifrs]
name = "IFRS"
desc = "International Financial Reporting Standards"
see = 'GAAP'
