[lof]
disp = "LOF"
desc = "Listed Open-Ended Fund"

[lse]
disp = "LSE"
desc = "London Stock Exchange"

[lme]
disp = "LME"
desc = "London Metal Exchange"

[lp]
disp = "LP"
desc = "Limited Partner"

[lpr]
disp = "LPR"
desc = "Loan Prime Rate"

[loop]
disp = "LOOP"
desc = "Law of one price"
