[lof]
name = "LOF"
desc = "Listed Open-Ended Fund"

[lse]
name = "LSE"
desc = "London Stock Exchange"

[lme]
name = "LME"
desc = "London Metal Exchange"

[lp]
name = "LP"
desc = "Limited Partner"

[lpr]
name = "LPR"
desc = "Loan Prime Rate"

[loop]
name = "LOOP"
desc = "Law of one price"

[llc]
name = "LLC"
desc = "Limited Liability Company"

[lbmn]
name = "LBMN"
desc = "London Bullion Market Association"

[lbs]
name = "LBS"
desc = "Location Based Services"
