[mpa]
name = "MPA"
desc = "Master of Public Administration"

[mba]
name = "MBA"
desc = "Master of Business Administration"

[mpm]
name = "MPM"
desc = "Master of Project Management"

[mem]
name = "MEM"
desc = "Master of Engineering Management"

[mvp]
name = "MVP"
desc = "Minimum Viable Product"

[mbo]
name = "MBO"
desc = "Management Buy-Outs"

[mlf]
name = "MLF"
desc = "Medium-term Lending Facility"

[mmf]
name = "MMF"
desc = "Money Market Fund"

[macd]
name = "MACD"
desc = "Moving Average Convergence Divergence"

[mib]
name = "MIB"
desc = "Milano Indice di Borsa"

[ma]
name = "MA"
desc = "Moving Average"

[msci]
name = "MSCI"
desc = "Morgan Stanley Capital International"

[mcn]
name = "MCN"
desc = "Multi-Channel Network"
