[mpa]
disp = "MPA"
desc = "Master of Public Administration"

[mba]
disp = "MBA"
desc = "Master of Business Administration"

[mpm]
disp = "MPM"
desc = "Master of Project Management"

[mem]
disp = "MEM"
desc = "Master of Engineering Management"

[mvp]
disp = "MVP"
desc = "Minimum Viable Product"

[mbo]
disp = "MBO"
desc = "Management Buy-Outs"

[mlf]
disp = "MLF"
desc = "Medium-term Lending Facility"

[mmf]
disp = "MMF"
desc = "Money Market Fund"

[macd]
disp = "MACD"
desc = "Moving Average Convergence Divergence"
