[nyse]
disp = "NYSE"
desc = "New York Stock Exchange"

[nasdaq]
disp = "NASDAQ"
desc = "National Association of Securities Dealers Automated Quotations"

[nft]
disp = "NFT"
desc = "Non-fungible Tokens"

[nymex]
disp = "NYMEX"
desc = "New York Mercantile Exchange"
