[nyse]
name = "NYSE"
desc = "New York Stock Exchange"

[nasdaq]
name = "NASDAQ"
desc = "National Association of Securities Dealers Automated Quotations"

[nasd]
name = "NASD"
desc = "National Association of Securities Dealers"

[nft]
name = "NFT"
desc = "Non-fungible Tokens"

[nymex]
name = "NYMEX"
desc = "New York Mercantile Exchange"

[nre]
name = "NRE"
desc = "Non-Recurring Engineering"

[npv]
name = "NPV"
desc = "Net Present Value"
