[o2o]
name = "O2O"
desc = "Online to offline"

[opec]
name = "OPEC"
desc = "Organization of the Petroleum Exporting Countries"

[otc]
name = "OTC"
desc = "Over-the-counter"
more = "A decentralized market (as opposed to an exchange market) where geographically dispersed dealers are linked by telephones and computers. The market is for securities not listed on a stock or derivatives exchange"

[odi]
name = "ODI"
desc = "Outward Direct Investment"
see = ['FDI']

[ogc]
name = "OGC"
desc = "Occupationally-generated Content"
