[ppi]
disp = "PPI"
desc = "Producer Price Index"

[pe]
same = 'P/E<=>p/e'

[per]
same = 'P/E<=>p/e'

['p/e']
disp = "P/E"
desc = "Price–to-Earnings Ratio"

[pb]
same = 'P/B<=>p/b'

[pbr]
same = 'P/B<=>p/b'

['p/b']
disp = "P/B"
desc = "Price-to-Book Ratio"

[pmp]
disp = "PMP"
desc = "Project Management Professional"

[pmi]
disp = "PMI"
desc = "Purchasing Managers' Index"
