[ppi]
name = "PPI"
desc = "Producer Price Index"

[pe]
same = 'P/E=>p/e'

[per]
same = 'P/E=>p/e'

['p/e']
name = "P/E"
desc = "Price–to-Earnings Ratio"

[pb]
same = 'P/B=>p/b'

[pbr]
same = 'P/B=>p/b'

['p/b']
name = "P/B"
desc = "Price-to-Book Ratio"

[pmp]
name = "PMP"
desc = "Project Management Professional"

[pmi]
name = "PMI"
desc = "Purchasing Managers' Index"

[pmi.Project]
name = "PMI"
desc = "Project Management Institute"

[pdm]
name = "PDM"
desc = "Precedence Diagramming Method"

[pert]
name = "PERT"
desc = "Program Evaluation and Review Technique"

[pgc]
name = "PGC"
desc = "Professionally Generated Content"

[pdca]
name = "PDCA"
desc = "Plan, Do, Check, Act"
