[ppi]
disp = "PPI"
desc = "Producer Price Index"

[pe]
same = 'p/e'

[per]
same = 'p/e'

['p/e']
disp = "P/E"
desc = "Price–to-Earnings Ratio"

[pb]
same = 'p/b'

[pbr]
same = 'p/b'

['p/b']
disp = "P/B"
desc = "Price-to-Book Ratio"
