[roa]
name = "ROA"
desc = "Return on Assets"

[roe]
name = "ROE"
desc = "Return on Equity"

[roc]
name = "ROC"
desc = "Return on Capital"

[roi]
name = "ROI"
desc = "Return on Investment"

[rpi]
name = "RPI"
desc = "Retail Price Index"

[rsi]
name = "RSI"
desc = "Relative Strength Index"

[rsv]
name = "RSV"
desc = "Raw Stochastic Value"
