[roe]
name = "ROE"
desc = "Return on Equity"

[roi]
name = "ROI"
desc = "Return on Investment"

[rpi]
name = "RPI"
desc = "Retail Price Index"

[rsi]
name = "RSI"
desc = "Relative Strength Index"

[rsv]
name = "RSV"
desc = "Raw Stochastic Value"
