[sse]
name = "SSE"
desc = "Shanghai Stock Exchange"

[szse]
name = "SZSE"
desc = "Shenzhen Stock Exchange"

[sec]
name = "SEC"
desc = "U.S. Securities and Exchange Commission"

[st]
name = "ST"
desc = "Special treatment"

[spif]
name = "SPIF"
desc = "Share Price Index Futures"

[shfe]
name = "SHFE"
desc = "Shanghai Futures Exchange"

[sdr]
name = "SDR"
desc = "Special Drawing Rights"

[swift]
name = "SWIFT"
desc = "Society for Worldwide Interbank Financial Telecommunication"

[swot]
name = "SWOT"
desc = "Strengths, Weaknesses, Opportunities, and Threats"

[spac]
name = "SPAC"
desc = "Special Purpose Acquisition Company"

[sku]
name = "SKU"
desc = "Stock Keeping Unit"
