[sse]
disp = "SSE"
desc = "Shanghai Stock Exchange"

[szse]
disp = "SZSE"
desc = "Shenzhen Stock Exchange"

[sec]
disp = "SEC"
desc = "U.S. Securities and Exchange Commission"

[st]
disp = "ST"
desc = "Special treatment"

