[sse]
disp = "SSE"
desc = "Shanghai Stock Exchange"

[szse]
disp = "SZSE"
desc = "Shenzhen Stock Exchange"

[sec]
disp = "SEC"
desc = "U.S. Securities and Exchange Commission"

[st]
disp = "ST"
desc = "Special treatment"

[spif]
disp = "SPIF"
desc = "Share Price Index Futures"

[shfe]
disp = "SHFE"
desc = "Shanghai Futures Exchange"

[sdr]
disp = "SDR"
desc = "Special Drawing Rights"
