[tse]
name = "TSE"
desc = "Tokyo Stock Exchange"

[ttm]
name = "TTM"
desc = "Trailing Twelve Months"

[tmt]
name = "TMT"
desc = "Technology，Media，Telecom"

[tfp]
name = "TFP"
desc = "Total Factor Productivity"

[tsx]
name = "TSX"
desc = "Toronto Stock eXchange"
