[wb]
name = "WB"
desc = "World Bank"

[wto]
name = "WTO"
desc = "World Trade Organization"

[wti]
name = "WTI"
desc = "West Texas Intermediate"

[wbs]
name = "WBS"
desc = "Work Breakdown Structure"

[wacc]
name = "WACC"
desc = "Weighted Average Cost of Capital"
